<script setup lang="ts">
// Componentes terminados: están documentados en docs/config/components.
// 'Accordion'
// 'Alert'
// 'AlertDialog'
// 'Announcer'
// 'AspectRatio'
// 'Attachment'
// 'Avatar'
// 'Badge'
// 'Bubble'
// 'Button'
// 'ButtonGroup'
// 'Card'
// 'Checkbox'
// 'Chip'
// 'Empty'
// 'FieldSet'
// 'Icon'
// 'Kbd'
// 'Label'
// 'Loading'
// 'Marker'
// 'Masonry'
// 'Message'
// 'Popover'
// 'Progress'
// 'Ribbon'
// 'ScrollArea'
// 'Search'
// 'Separator'
// 'Slider'
// 'Splitter'
// 'Switch'
// 'Textarea'
</script>

<template />
