export const ratingDefaults = {
  length: 5,
  clearable: false,
  hoverable: false,
  loop: false,
  disabled: false,
  readonly: false,
  required: false,
  name: undefined,
  step: 1 as const,
  orientation: 'horizontal' as const,
  size: 'md' as const,
  severity: 'primary' as const,
  color: undefined,
  icon: 'star' as const,
}
