export const linearChartCurveTypes = [
  'basis',
  'basisClosed',
  'basisOpen',
  'bundle',
  'cardinal',
  'cardinalClosed',
  'cardinalOpen',
  'catmullRom',
  'catmullRomClosed',
  'catmullRomOpen',
  'linear',
  'linearClosed',
  'monotoneX',
  'monotoneY',
  'natural',
  'step',
  'stepAfter',
  'stepBefore',
] as const

export const linearChartDefaults = {
  height: 320,
  color: 'var(--chart-1)',
  lineWidth: 2,
  curveType: 'linear' as const,
  interpolateMissingData: false,
  fallbackValue: undefined,
  highlightOnHover: false,
  cursor: undefined,
  tooltip: false,
  crosshair: false,
  yDomain: undefined,
  gridLine: true,
}
